apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-dog
spec:
  selector:
    matchLabels:
      app: bd-dog
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: bd-dog
    spec:
      containers:
        - name: bd-dog
          image: pelsan/otumbaparent-dog:latest
          env:
            - name: SPRING_PROFILE
              value: dev
            - name: SPRING_APPLICATION_JSON
              valueFrom:
                configMapKeyRef:
                  name: spring-config-dog
                  key: dev-config.json
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: bd-dog-service
spec:
  selector:
    app: bd-dog
  ports:
    - name: http
      port: 8093
      nodePort: 31093
  type: NodePort