server:
  port: 8091
---
springdoc:
  swagger-ui:
    path: /swagger/index.html
    enabled: true
---
example:
  datasource:
    url: jdbc:mysql://localhost/example
    username: local-user
    password: local-password

---
spring:
  config:
    activate:
      on-profile: dev 
  datasource:
    url: ${example.datasource.url}
    username: ${example.datasource.username}
    password: ${example.datasource.password}